Transform: 'AWS::Serverless-2016-10-31'
Description: serverless specification for squire bots
Resources:
  NumpyLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile
  PandasLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile
  OpenaiLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile
  PynaclLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile
  CommandFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.command
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          OPENAI_API_KEY:
            Ref: OpenaiApiKeyParameter
      Layers:
        - Ref: NumpyLayer
        - Ref: PandasLayer
        - Ref: OpenaiLayer
    Metadata:
      BuildMethod: makefile
  InteractionFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.interaction
      Runtime: python3.9
      MemorySize: 128
      Timeout: 3
      Events:
        SquireApi:
          Type: Api
          Properties:
            Path: /interactions
            Method: POST
      Policies:
        - LambdaInvokePolicy:
            FunctionName:
              Ref: SquireCommandFunction
      Environment:
        Variables:
          DISCORD_PUBLIC_KEY:
            Ref: DiscordPublicKeyParameter
          COMMAND_LAMBDA_ARN:
            Ref: CommandFunction
      Layers:
        - Ref: PynaclLayer
    Metadata:
      BuildMethod: makefile
Parameters:
  DiscordPublicKeyParameter:
    Type: String
    Description: discord public key used to authenticate from-discord post requests (found in Application -> General Information)
  OpenaiApiKeyParameter:
    Type: String
    Description: openai key used to make requests to the openai api